import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

// Define strict styles for PDF (Flexbox-like)
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Inter" },
  header: {
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
    paddingBottom: 10,
  },
  companyName: { fontSize: 24, fontWeight: "bold", color: "#111" },
  subtitle: { fontSize: 10, color: "#666", marginTop: 4 },

  section: { marginBottom: 20 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#333",
  },

  scoreCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#F8FAFC",
    padding: 15,
    borderRadius: 8,
  },
  scoreBox: { alignItems: "center" },
  scoreVal: { fontSize: 28, fontWeight: "bold", color: "#2563EB" },
  scoreLabel: { fontSize: 10, color: "#64748B" },

  text: { fontSize: 11, lineHeight: 1.5, color: "#334155" },
});

interface ReportProps {
  candidateName: string;
  roleName: string;
  totalScore: number;
  aiSummary: string;
}

// The PDF Document Structure
export const InterviewReportPDF = ({
  candidateName,
  roleName,
  totalScore,
  aiSummary,
}: ReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* HEADER */}
      <View style={styles.header}>
        <Text style={styles.companyName}>HireAI Report</Text>
        <Text style={styles.subtitle}>
          Interview Result for {candidateName} • {roleName}
        </Text>
      </View>

      {/* SCORE SECTION */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Performance Overview</Text>
        <View style={styles.scoreCard}>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreVal}>{totalScore}%</Text>
            <Text style={styles.scoreLabel}>Overall Score</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreVal}>Passed</Text>
            <Text style={styles.scoreLabel}>AI Recommendation</Text>
          </View>
        </View>
      </View>

      {/* SUMMARY SECTION */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>AI Summary</Text>
        <Text style={styles.text}>{aiSummary}</Text>
      </View>

      {/* FOOTER */}
      <Text
        style={{
          position: "absolute",
          bottom: 30,
          left: 40,
          fontSize: 8,
          color: "#AAA",
        }}
      >
        Generated by HireAI • Confidential Document
      </Text>
    </Page>
  </Document>
);
